//! A small made-up colony for tests, fixtures, and Hill's `--sample` mode. Never anyone's real
//! colony: it is generated by `formiga-core` from fixed seeds, so it is the same every time.

use crate::{ExportOptions, SessionId, TravelSnapshot, export_snapshot};
use formiga_core::{
    Accessory, AccessoryKind, CreatureRelationship, DesktopSnapshot, Habit, SaveFile, World,
};
use sha2::{Digest, Sha256};
use time::{OffsetDateTime, macros::datetime};

const CREATED_AT: OffsetDateTime = datetime!(2026-10-02 12:00 UTC);
const SESSION: SessionId = SessionId::from_bytes(*b"formiga-hill-smp");

/// Four adults with a hat, a couple of habits, and bonds of every sort between them.
pub fn save() -> SaveFile {
    let desktop = DesktopSnapshot::default();
    let mut world = World::new(seed(0), CREATED_AT, &desktop);
    for n in 1..4 {
        world
            .add_designed_adult(seed(n), None, CREATED_AT, &desktop)
            .expect("a new colony has room for four");
    }
    let mut save = world.save;

    save.creatures[0].accessory = Some(Accessory::Worn(AccessoryKind::LeafHat));
    save.creatures[2].accessory = Some(Accessory::Worn(AccessoryKind::KnittedScarf));
    save.creatures[1].memory.habits = vec![Habit::WavesHello];
    save.creatures[3].memory.habits = vec![Habit::LooksFoodOver, Habit::CirclesBeforeNaps];

    // Every pair, from strangers to best friends to a pair that squabbles.
    let ids: Vec<_> = save.creatures.iter().map(|creature| creature.id).collect();
    save.relationships.clear();
    let mut scores = [
        (200, 180, 140, 0),
        (90, 120, 40, 10),
        (10, 20, 0, 0),
        (60, 140, 160, 130),
        (130, 90, 70, 20),
        (30, 60, 10, 70),
    ]
    .into_iter();
    for (i, &a) in ids.iter().enumerate() {
        for &b in &ids[i + 1..] {
            let (affinity, familiarity, playfulness, avoidance) = scores.next().unwrap_or_default();
            if let Some(relationship) = CreatureRelationship::new(a, b) {
                save.relationships.push(CreatureRelationship {
                    affinity,
                    familiarity,
                    playfulness,
                    avoidance,
                    ..relationship
                });
            }
        }
    }
    save
}

/// The sample colony, boarded.
pub fn snapshot() -> TravelSnapshot {
    export_snapshot(
        &save(),
        ExportOptions {
            session_id: SESSION,
            created_at_utc: CREATED_AT,
            desktop_version: "sample colony".to_owned(),
        },
    )
}

fn seed(n: u8) -> [u8; 32] {
    Sha256::new()
        .chain_update(b"formiga-hill/sample-colony")
        .chain_update([n])
        .finalize()
        .into()
}
